package led

enum class ProcedureBundleFields {
    COLOR_PRIMARY, COLOR_SECONDARY, COLOR_TERTIARY,
    VALUE_1, VALUE_2, VALUE_3,
    STRIP, CALLBACK,
    MODULO, INTERPOLATION, DIRECTION, BPM, REPETITIONS, SPEED, DURATION, PATH,
    SUB_BUNDLE, IS_SUB_PROCEDURE,

    //Post Update Fields
    PU_MODULO, PU_MODULO_INVERT
}